### ISSUE TITLE
Addition of Blog section required.

### ISSUE THREAD

**Issue by Zeeshan-2k1** [hnccbits/contest.hnccbits.com#14]
A blog section is to be added before footer. Can be made by using [Card](https://material-ui.com/components/cards/) of Material-UI

**Comment by AnandBIT** [comment]
I've added the blog section
Check, if the issue is solved, then please close this issue

**Comment by AnandBIT** [comment]
I've added the blog section
Please check @Zeeshan-2k1 @suraj-sloth 
If the issue is solved, then please close this issue

**Comment by Zeeshan-2k1** [comment]
Nice @AnandBIT. Working good.

**Comment by Zeeshan-2k1** [comment]
@suraj-sloth Content needed here and check for responisveness.
