### ISSUE TITLE
Create the Nav Bar using Material UI React Component or Bootstrap Nav.

### ISSUE THREAD

**Issue by suraj-sloth** [hnccbits/contest.hnccbits.com#2]
I have added the Material UI cdn. If that doesn't works add material-ui using npm. [Material UI Site link](https://material-ui.com/)

You can use this App Bar instead of Nav - [https://material-ui.com/components/app-bar/](https://material-ui.com/components/app-bar/)

**Comment by Zeeshan-2k1** [comment]
@AnandBIT can you please look after navbar svgs and styling.

**Comment by suraj-sloth** [comment]
@Zeeshan-2k1 Great work to add labels to the issues :)

**Comment by Zeeshan-2k1** [comment]
Navbar completed.
