### ISSUE TITLE
Create the Header according to the UX.

### ISSUE THREAD

**Issue by suraj-sloth** [hnccbits/contest.hnccbits.com#3]
[UX Link](https://xd.adobe.com/view/12db09fc-5a0f-42c9-b5aa-a984e4c852b5-4788/specs/)
Take the Colors from specs view mode.
Header.js is already created.

**Comment by Zeeshan-2k1** [comment]
Styling of header section is needed for responsive view.

**Comment by Zeeshan-2k1** [comment]
Worked over it. Issue resolved in pull request #21.
