### ISSUE TITLE
Modify the Leaderboard Section with styling.

### ISSUE THREAD

**Issue by suraj-sloth** [hnccbits/contest.hnccbits.com#4]
[UX Mockup Link](https://xd.adobe.com/view/12db09fc-5a0f-42c9-b5aa-a984e4c852b5-4788/)

**Comment by Zeeshan-2k1** [comment]
Commented out the previous available data in App.js

**Comment by Zeeshan-2k1** [comment]
Review of this segemnt is needed @suraj-sloth
