### ISSUE TITLE
Footer and the Blog Section using Material-ui or Bootstrap

### ISSUE THREAD

**Issue by suraj-sloth** [hnccbits/contest.hnccbits.com#6]
[Bottom Navigation Docs Link](https://material-ui.com/components/bottom-navigation/)

**Comment by Zeeshan-2k1** [comment]
I want to take this @suraj-sloth

**Comment by suraj-sloth** [comment]
Ok carry on with this. You should also take the leaderboard section.

**Comment by Zeeshan-2k1** [comment]
Additonal Content Required for footer.

**Comment by Zeeshan-2k1** [comment]
Footer section is complete.
